### ISSUE TITLE
Kelp crashes whenever horizon is down (every 2 weeks so far)

### ISSUE THREAD

**Issue by skirsch** [lightyeario/kelp#43]
// see a sample bug report here: https://github.com/lightyeario/kelp/issues/1

## Describe the bug
kelp crashes after running for 2 weeks because horizon is down. 

2018/10/30 15:27:44 error decoding horizon.Problem: EOF
2018/10/30 15:27:44 Can't load offers: error decoding horizon.Problem: EOF
2018/10/30 15:27:44 error decoding horizon.Problem: EOF
2018/10/30 15:27:44 Can't load offers: error decoding horizon.Problem: EOF
2018/10/30 15:27:44 error: cannot load offers to compute liabilities for asset (USD:GDSRCV5VTM3U7Y3L6DFRP3PEGBNQMGOWSRTGSBWX6Z3H6C7JHRI4XFJP): error decoding horizon.Problem: EOF
2018/10/30 15:27:44 liabilities after resetting
2018/10/30 15:27:44 Can't load offers: error decoding horizon.Problem: EOF
2018/10/30 15:27:44 error: cannot load offers to compute liabilities for asset (USD:GDSRCV5VTM3U7Y3L6DFRP3PEGBNQMGOWSRTGSBWX6Z3H6C7JHRI4XFJP): error decoding horizon.Problem: EOF
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x75a88b]

## Expected behavior
// A succinct description of **what you expected to happen**.
This happened before on 10/17. It happened to me again on 10/30.  why not just catch the error and try again the next interval?

## Frequency
The frequency is: sometimes

## Steps To Reproduce
start with the buysell and let it run for 10 days

## Possible Solution
// Optional, suggest a fix.

This bug can be fixed by ...

## Your Environment
// Run `kelp version` to get the version and build information and paste it here
stk@steve-kelp:~/kelp$ ./kelp version
  version: v1.0.0-rc3
  git hash: c8363e74c80cc3854dfbf19110f10b8ad21fe3d4
  build date: 20180929T155837Z
  GOOS: linux
  GOARCH: amd64

...

## Context
// A succinct description of how has this bug has **affected you** or prevented you from accomplishing what you wanted.

I am unable to keep trading

## Attachments
// Attach any relevant configuration files, logs, tx hashes, etc. here.
[logfile.txt](https://github.com/lightyeario/kelp/files/2545589/logfile.txt)

**Comment by nikhilsaraf** [comment]
will look into this.

**Comment by PedityOfficial** [comment]
Hi @nikhilsaraf 
This is the same issue #27 
This happened again, i hope we can have a timeout and retry if horizon is down.

**Comment by nikhilsaraf** [comment]
@skirsch @PedityOfficial I looked into the issue and it's already been fixed in the master branch (a69a226661a21eb9e50665c70ca8cca646a12781) so there's no more code changes needed to address this issue.

I tested by turning my internet connection off and the bot did not crash. It seamlessly picked back up from where it left off once it regained access to the internet. I think this is good enough to mark this issue as closed.

I'll be releasing a new version of Kelp pretty soon that will include this fix along with many other improvements and bug fixes. You can either wait for that (see [link to announcements distribution list](https://github.com/lightyeario/kelp#communication)) or compile from the master branch to get the fix quicker.
